require "user.impatient"
require "user.personal.keymaps"
require "user.personal.options-base"
require "user.plugins-setup"
require "user.util.autocommands"
require "user.cmp"
require "user.colorscheme"
