pcall(require, "luarocks.loader")
require("awful.autofocus")
require("awful.hotkeys_popup.keys")
require("personal.error_handling")
require("personal.themes")
require("personal.layout")
require("personal.screen")
require("personal.mouse_binding")
require("personal.key_bindings")
require("personal.rules")
require("personal.signals")
require("personal.automatic_start")
