complete -c ai-jail -f

complete -c ai-jail -n "__fish_use_subcommand" -a "claude codex opencode crush bash status" -d "Known command preset"

complete -c ai-jail -l rw-map -r -a "(__fish_complete_directories)" -d "Mount path read-write"
complete -c ai-jail -l map -r -a "(__fish_complete_directories)" -d "Mount path read-only"
complete -c ai-jail -l lockdown -d "Enable lockdown"
complete -c ai-jail -l no-lockdown -d "Disable lockdown"
complete -c ai-jail -l landlock -d "Enable Landlock"
complete -c ai-jail -l no-landlock -d "Disable Landlock"
complete -c ai-jail -l gpu -d "Enable GPU passthrough"
complete -c ai-jail -l no-gpu -d "Disable GPU passthrough"
complete -c ai-jail -l docker -d "Enable Docker passthrough"
complete -c ai-jail -l no-docker -d "Disable Docker passthrough"
complete -c ai-jail -l display -d "Enable display passthrough"
complete -c ai-jail -l no-display -d "Disable display passthrough"
complete -c ai-jail -l mise -d "Enable mise integration"
complete -c ai-jail -l no-mise -d "Disable mise integration"
complete -c ai-jail -l clean -d "Ignore existing config"
complete -c ai-jail -l dry-run -d "Print sandbox command"
complete -c ai-jail -l init -d "Create or update .ai-jail"
complete -c ai-jail -l bootstrap -d "Generate AI tool configs"
complete -c ai-jail -s v -l verbose -d "Show detailed mount info"
complete -c ai-jail -s h -l help -d "Show help"
complete -c ai-jail -s V -l version -d "Show version"
