# Lazy-load `codex` completions (generated by `codex completion fish`).
# This keeps the completion definitions in sync with the installed codex version.

status --is-interactive; or return
type -q codex; or return

if set -q __codex_fish_completion_loaded
    return
end
set -g __codex_fish_completion_loaded 1

codex completion fish | source
