# Fish completions for warp-cli (generated from zsh completions)
# Global flags
complete -c warp-cli -n "__fish_use_subcommand" -s t -l timeout -d "IPC timeout in seconds"
complete -c warp-cli -n "__fish_use_subcommand" -s l -l listen -d "Listen for status changes"
complete -c warp-cli -n "__fish_use_subcommand" -l accept-tos -d "Accept Terms of Service"
complete -c warp-cli -n "__fish_use_subcommand" -s v -l verbose -d "Enable verbose output"
complete -c warp-cli -n "__fish_use_subcommand" -s j -l json -d "JSON output"
complete -c warp-cli -n "__fish_use_subcommand" -l no-paginate -d "Disable pagination"
complete -c warp-cli -n "__fish_use_subcommand" -l no-ansi -d "Disable ANSI colors"
complete -c warp-cli -n "__fish_use_subcommand" -s h -l help -d "Show help"
complete -c warp-cli -n "__fish_use_subcommand" -s V -l version -d "Show version"

# Main commands
complete -c warp-cli -n "__fish_use_subcommand" -a "connect" -d "Maintain connection"
complete -c warp-cli -n "__fish_use_subcommand" -a "debug" -d "Debugging commands"
complete -c warp-cli -n "__fish_use_subcommand" -a "disconnect" -d "Disconnect client"
complete -c warp-cli -n "__fish_use_subcommand" -a "dns" -d "Configure DNS settings"
complete -c warp-cli -n "__fish_use_subcommand" -a "environment" -d "Configure compliance environment"
complete -c warp-cli -n "__fish_use_subcommand" -a "mdm" -d "MDM configs"
complete -c warp-cli -n "__fish_use_subcommand" -a "mode" -d "Set operating mode"
complete -c warp-cli -n "__fish_use_subcommand" -a "override" -d "Override admin settings"
complete -c warp-cli -n "__fish_use_subcommand" -a "proxy" -d "Configure proxy mode"
complete -c warp-cli -n "__fish_use_subcommand" -a "registration" -d "Registration settings"
complete -c warp-cli -n "__fish_use_subcommand" -a "connector" -d "Register WARP Connector"
complete -c warp-cli -n "__fish_use_subcommand" -a "settings" -d "Show or alter settings"
complete -c warp-cli -n "__fish_use_subcommand" -a "status" -d "Return connection status"
complete -c warp-cli -n "__fish_use_subcommand" -a "target" -d "Manage targets"
complete -c warp-cli -n "__fish_use_subcommand" -a "trusted" -d "Configure trusted networks"
complete -c warp-cli -n "__fish_use_subcommand" -a "tunnel" -d "Configure tunnel settings"
complete -c warp-cli -n "__fish_use_subcommand" -a "vnet" -d "Manage virtual network"
complete -c warp-cli -n "__fish_use_subcommand" -a "generate-completions" -d "Generate shell completions"
complete -c warp-cli -n "__fish_use_subcommand" -a "stats" -d "Display statistics"
complete -c warp-cli -n "__fish_use_subcommand" -a "certs" -d "Print installed certificates"
complete -c warp-cli -n "__fish_use_subcommand" -a "help" -d "Print help"
